---
- hosts: thispc
  become: yes

  vars:
      - user: tato

  roles:

    - role: geerlingguy.git
      git_packages:
          - git

    - role: geerlingguy.docker
      docker_users:
          - "{{ user }}"

    - role: sansible.golang
      sansible_golang_workspace_user: "{{ user }}" 

    - role: gantsign.visual-studio-code
      users:
      - username: "{{ user }}"

    - role: gantsign.visual-studio-code-extensions
      users:
          - username: "{{ user }}"
            visual_studio_code_extensions:
                - ms-python.python
                - ms-vscode.cpptools
                - ms-vscode.Go
    tasks:
    
    - name: Install Python 3.6 (via APT), please revise this
      apt:
        - name: python3.6
          state: latest
