---
- hosts: thispc
  become: yes

  vars:
      - user: tato

  roles:

    - role: geerlingguy.git
      git_packages:
          - git

    - role: geerlingguy.docker
      docker_users:
          - "{{ user }}"

    - role: gantsign.visual-studio-code
      users:
      - username: "{{ user }}"

    - role: gantsign.visual-studio-code-extensions
      users:
          - username: "{{ user }}"
            visual_studio_code_extensions:
                - ms-vscode.csharp
                - ms-python.python
                - ms-vscode.cpptools
                - ms-vscode.Go
                - rust-lang.rust
                - peterjausovec.vscode-docker

    - role: naftulikay.rust-dev
      rust_user: "{{ user }}"

    - role: fubarhouse.golang
      go_install_clean: true
      go_version: 1.12.2
