---
- hosts: thispc
  become: yes

  vars:
      - user: tato

  roles:

    - role: geerlingguy.git
      git_packages:
          - git

    - role: geerlingguy.docker
      docker_users:
          - "{{ user }}"
      docker_package_state: latest
      docker_install_compose: true
      docker_compose_version: "1.26.0-rc3"

    - role: gantsign.visual-studio-code
      users:
      - username: "{{ user }}"
      visual_studio_code_version: ''
      visual_studio_code_build: insiders

    - role: gantsign.visual-studio-code-extensions
      users:
          - username: "{{ user }}"
            visual_studio_code_extensions:
                - ms-python.python
                - ms-vscode.cpptools
                - ms-vscode.Go
                - rust-lang.rust
                - ms-azuretools.vscode-docker
                - ms-vscode.cmake-tools
                - ms-vscode-remote.remote-containers

    - role: naftulikay.rust-dev
      rust_user: "{{ user }}"

    - role: fubarhouse.golang
      go_install_clean: true
      go_version: 1.13.3
      golang_shell_profile: "/home/{{ user }}/.profile"
      GOPATH: "/home/{{ user }}/go"

    - role: albanandrieu.cmake
      cmake_enabled: true
